.github/workflows/maven.yml
This is a simple first action for having Maven run the unit tests
=> Add GitHub actions

README.md
I meant to have this in there before transferring ownership of the repo... oops.
=> Add applier instructions to README

src/main/resources/META-INF/openapi.yml
So the frontend knows how to talk to the backend.
=> Add OpenAPI spec for the "residency" object

deployment/templates/deploymentconfig.yaml
So we don't have to keep messing with the deployment
=> Switch from env to envfrom

.github/workflows/pull-request-checks.yml
@jacobsee let me know if there are more files or directories we should add
=> Don't trigger builds when only certain directories have been changed

scripts/get-token.sh, src/main/java/com/redhat/labs/omp/model/Engagement.java, src/main/java/com/redhat/labs/omp/model/EngagementUser.java, src/main/java/com/redhat/labs/omp/model/Launch.java, src/main/java/com/redhat/labs/omp/model/Version.java, src/main/java/com/redhat/labs/omp/resource/ConfigResource.java, src/main/java/com/redhat/labs/omp/resource/EngagementResource.java, src/main/java/com/redhat/labs/omp/resource/GitSyncResource.java
- jwt token can be added to swagger to be used for protected endpoints
- added script for just getting token to use for swagger-ui
- added descriptions and responses to each endpoint
- added jsonb property annotations so open api docs are correct.  could not figure out how to use the jsonb config for quarkus
=> Open API and Swagger Updates

src/main/resources/META-INF/resources/index.html
* removes invalid data on the landing page
* gets the versions api info and displays
* directs user to this github repo.
* adds RH icon
=> remedial info on landing

README.md, src/main/java/com/redhat/labs/omp/rest/client/OMPGitLabAPIService.java, src/main/java/com/redhat/labs/omp/service/ConfigService.java, src/main/resources/application.properties, src/test/java/com/redhat/labs/omp/rest/client/MockOMPGitLabAPIService.java
- removed gitlab configurations from backend
- switched to use new `/config` endpoint from Git API for config
=> Removed Gitlab Configuration from Backend

pom.xml
Replacing version removed during conflict resolution.
=> Fix for Missing Plugin Version

src/main/java/com/redhat/labs/omp/repository/EngagementRepository.java, src/main/java/com/redhat/labs/omp/resource/EngagementResource.java, src/main/java/com/redhat/labs/omp/service/EngagementService.java, src/test/java/com/redhat/labs/omp/resources/CustomerSuggestionTest.java, src/test/java/com/redhat/labs/omp/resources/EngagementResourceTest.java
- New API for retrieving customer names based on the input of the user. For autosuggest feature
=> api for getting a list of customer name matches

src/main/java/com/redhat/labs/omp/model/CreationDetails.java, src/main/java/com/redhat/labs/omp/model/Engagement.java, src/main/java/com/redhat/labs/omp/service/GitSyncService.java, src/test/java/com/redhat/labs/omp/socket/EngagementEventSocketTest.java
- added created by user/email and created timestamp to the `engagement`
=> Creation Details for Engagement

src/main/java/com/redhat/labs/omp/resource/StatusResource.java, src/main/java/com/redhat/labs/omp/rest/client/OMPGitLabAPIService.java, src/main/java/com/redhat/labs/omp/service/ActiveGitSyncService.java, src/main/java/com/redhat/labs/omp/service/EngagementService.java, src/main/java/com/redhat/labs/omp/service/GitSyncService.java, src/main/resources/META-INF/resources/socket-test.html, src/test/java/com/redhat/labs/omp/rest/client/MockOMPGitLabAPIService.java
- Will check gitlab if it cannot find a project when processing hook. Can happen when special chars are involved as engagements are not 1:1 exact at the group level.
- turn down a couple of the noisier log outs
- update socket helper
- close hanging resource with try-with-resources pattern
=> Hook namespace

src/main/java/com/redhat/labs/omp/model/Message.java, src/main/java/com/redhat/labs/omp/model/Subsystem.java
=> Status Model Updates

src/main/java/com/redhat/labs/omp/model/Engagement.java, src/main/java/com/redhat/labs/omp/resource/EngagementResource.java, src/test/java/com/redhat/labs/omp/resources/EngagementResourceTest.java, src/test/resources/jwt/user-claims/JwtClaimsAllNoNameBlankUsername.json, src/test/resources/jwt/user-claims/JwtClaimsAllNoNameEmptyUsername.json, src/test/resources/jwt/user-claims/JwtClaimsAllNoNameNoUsername.json, src/test/resources/jwt/user-claims/JwtClaimsAllNoNameNoUsernameBlankEmail.json, src/test/resources/jwt/user-claims/JwtClaimsAllNoNameNoUsernameEmptyEmail.json, src/test/resources/jwt/user-claims/JwtClaimsAllNoNameNoUsernameNoEmail.json, src/test/resources/jwt/user-claims/JwtClaimsAllWithBlankNameClaim.json, src/test/resources/jwt/user-claims/JwtClaimsAllWithEmptyNameClaim.json, src/test/resources/jwt/user-claims/JwtClaimsAllWithNameClaim.json, src/test/resources/jwt/user-claims/JwtClaimsAllWithNoNameClaim.json
- Sets last updated user using the claims in the token
-  uses `user` claim if valid
-  uses `preferred_username` claim if `user` claim not valid
-  uses `email` claim if `user` or `preferred_username` not valid
- associated tests
- last updated by user and email now available in JSON
=> Setting of Last Updated User

src/main/java/com/redhat/labs/omp/model/Engagement.java, src/test/java/com/redhat/labs/omp/service/ActiveGitSyncServiceTest.java
=> additional info field

src/main/java/com/redhat/labs/omp/model/Subsystem.java
- moved urls into list of maps to match the agreed on format
=> Updates to Status Subsystem 

src/main/java/com/redhat/labs/omp/model/Engagement.java, src/main/java/com/redhat/labs/omp/service/EngagementService.java
- added `region` and `type` to engagement
- added trim to engagement key fields: `customerName` and `projectName`
=> Added New Engagement Fields

.github/workflows/ci-cd.yml, deployment/values-dev.yaml, pom.xml, src/main/resources/application.properties, src/test/resources/application.properties
- use Java 11
- use Quarkus 1.6.1.Final
- upgrade to Mongo Client v4.x requires specifying `uuidRepresentation`
=> Use Supported Java Version and Latest Quarkus Version

.github/workflows/ci-cd.yml, .github/workflows/release.yml, deployment/README.md, deployment/values-dev.yaml, deployment/values.yaml
This PR renames images from omp to lodestar. Affects .github/workflows and deployment/values.
=> Rename images 

pom.xml
Revert sonarcloud token  change
=> Revert sonarcloud token

src/main/java/com/redhat/labs/omp/model/Category.java, src/main/java/com/redhat/labs/omp/model/Engagement.java, src/main/java/com/redhat/labs/omp/model/event/BackendEvent.java, src/main/java/com/redhat/labs/omp/model/event/EventType.java, src/main/java/com/redhat/labs/omp/repository/CategoryRepository.java, src/main/java/com/redhat/labs/omp/resource/EngagementResource.java, src/main/java/com/redhat/labs/omp/service/CategoryService.java, src/main/java/com/redhat/labs/omp/service/EngagementService.java, src/test/java/com/redhat/labs/omp/resources/EngagementResourceTest.java, src/test/java/com/redhat/labs/omp/service/CategoryServiceTest.java
- `GET /engagements/categories`
- with no query parameters, all categories will be returned
- with `suggest` query parameter, only categories matching the value of the param will be returned
- associated tests
=> Category APIs

src/main/java/com/redhat/labs/lodestar/model/Artifact.java
Added `id` and `description` to artifact model.
=> New Fields for Artifacts

src/main/java/com/redhat/labs/lodestar/model/Engagement.java, src/test/java/com/redhat/labs/lodestar/resources/EngagementResourceTest.java
=> add public reference field to engagement

src/main/java/com/redhat/labs/lodestar/model/Engagement.java, src/main/java/com/redhat/labs/lodestar/model/EngagementUser.java, src/test/java/com/redhat/labs/lodestar/resources/EngagementResourceTest.java
- changed engagementUsers to be a Set instead of list
- updated EngagementUser equals/hashcode to only used email
- added duplicate PUT unit test
=> Duplicate Users Should be Ignored

src/main/java/com/redhat/labs/lodestar/resource/EngagementResource.java
- added `PUT` `/engagements/uuids/set` so that the process can be manually started.
=> Added API to Start UUID Setting Process

src/main/java/com/redhat/labs/lodestar/repository/EngagementRepository.java, src/main/java/com/redhat/labs/lodestar/resource/EngagementResource.java, src/main/java/com/redhat/labs/lodestar/service/EngagementService.java, src/test/java/com/redhat/labs/lodestar/resources/EngagementResourceTest.java, src/test/java/com/redhat/labs/lodestar/resources/GitSyncResourceTest.java, src/test/java/com/redhat/labs/lodestar/resources/StatusResourceTest.java
This PR should replace https://github.com/rht-labs/lodestar-backend/pull/116.
Same changes as 116 with the following modifications:
- changed the mongo query to use a case insensitive search
- using WebApplicationException instead of the removed Exception
- put subdomain validation into their own methods.
=> Check subdomain on Create/Update

src/main/java/com/redhat/labs/lodestar/resource/EngagementResource.java
Adds timers and counters for the engagement resource
=> add timers and counters for engagements

src/main/java/com/redhat/labs/lodestar/service/EngagementService.java, src/test/java/com/redhat/labs/lodestar/service/EngagementServiceTest.java
if launch object is not null for both incoming and persisted, the persisted version will be used.  otherwise, the incoming will be used.
launch --> incoming not null, existing null --> use incoming
not launched --> incoming null, existing null --> use incoming
reset  launch -->  incoming null, existing not null --> use incoming
launch modified --> incoming not null, existing not null --> use existing (doesn't allow modifications)
=> Allow Launch Rest to Only Null

deployment/templates/deploymentconfig.yaml, pom.xml, src/main/java/com/redhat/labs/lodestar/model/event/EventType.java, src/main/java/com/redhat/labs/lodestar/model/filter/FilterOptions.java, src/main/java/com/redhat/labs/lodestar/repository/EngagementRepository.java, src/main/java/com/redhat/labs/lodestar/resource/RefreshResource.java, src/main/java/com/redhat/labs/lodestar/rest/client/EngagementStatusApiClient.java, src/main/java/com/redhat/labs/lodestar/service/ActiveGitSyncService.java, src/main/java/com/redhat/labs/lodestar/service/EngagementService.java, src/main/java/com/redhat/labs/lodestar/service/EventService.java, src/main/java/com/redhat/labs/lodestar/util/ClassFieldUtils.java, src/main/resources/application.properties, src/test/java/com/redhat/labs/lodestar/resource/RefreshResourceTest.java, src/test/java/com/redhat/labs/lodestar/resource/StatusResourceTest.java, src/test/java/com/redhat/labs/lodestar/service/ActiveGitSyncServiceTest.java, src/test/java/com/redhat/labs/lodestar/service/EngagementServiceTest.java, src/test/java/com/redhat/labs/lodestar/service/EventServiceTest.java, src/test/java/com/redhat/labs/lodestar/utils/IntegrationTestHelper.java
engagement service will be active with this PR and required to be deployed.
=> Quarkus v2 + Engagement Status Service

src/main/java/com/redhat/labs/lodestar/resource/EngagementResource.java, src/main/java/com/redhat/labs/lodestar/service/EngagementService.java, src/test/java/com/redhat/labs/lodestar/resource/EngagementResourceGetTest.java
- ability to filter by region when counting engagement state
=> add region filter for engagement count

src/main/java/com/redhat/labs/lodestar/model/Engagement.java
=> fix missing engagement type

src/main/java/com/redhat/labs/lodestar/model/event/EventType.java, src/main/java/com/redhat/labs/lodestar/resource/ConfigResource.java, src/main/java/com/redhat/labs/lodestar/resource/HostingResource.java, src/main/java/com/redhat/labs/lodestar/resource/RefreshResource.java, src/main/java/com/redhat/labs/lodestar/rest/client/CategoryApiClient.java, src/main/java/com/redhat/labs/lodestar/rest/client/ConfigApiClient.java, src/main/java/com/redhat/labs/lodestar/service/ConfigService.java, src/main/java/com/redhat/labs/lodestar/service/HostingService.java, src/test/java/com/redhat/labs/lodestar/resource/ConfigResourceTest.java, src/test/resources/config-artifact-options.json, src/test/resources/config-engagement-options.json, src/test/resources/config-region-options.json
- Add ability to refresh hosting env
- adds ability to get key / value options from config service
=> Add ability to refresh hosting env

src/main/java/com/redhat/labs/lodestar/model/Artifact.java, src/main/java/com/redhat/labs/lodestar/model/EngagementArtifact.java, src/main/java/com/redhat/labs/lodestar/service/ArtifactService.java, src/test/java/com/redhat/labs/lodestar/service/ArtifactServiceTest.java
Add a little extra data to artifacts on request. A display value of type and the region
=> add region and nice type to artifact api

src/main/java/com/redhat/labs/lodestar/resource/EngagementResource.java, src/main/java/com/redhat/labs/lodestar/rest/client/EngagementApiClient.java, src/main/java/com/redhat/labs/lodestar/service/EngagementService.java, src/test/java/com/redhat/labs/lodestar/resource/EngagementResourceCountTest.java
=> filter engagement counts by region

pom.xml, src/main/java/com/redhat/labs/lodestar/model/Author.java, src/main/java/com/redhat/labs/lodestar/model/Engagement.java, src/main/java/com/redhat/labs/lodestar/model/EngagementAttribute.java, src/main/java/com/redhat/labs/lodestar/model/EngagementUser.java, src/main/java/com/redhat/labs/lodestar/resource/ArtifactResource.java, src/main/java/com/redhat/labs/lodestar/resource/EngagementResource.java, src/main/java/com/redhat/labs/lodestar/rest/client/EngagementApiClient.java, src/main/java/com/redhat/labs/lodestar/rest/client/UseCaseApiClient.java, src/main/java/com/redhat/labs/lodestar/service/ActivityService.java, src/main/java/com/redhat/labs/lodestar/service/ArtifactService.java, src/main/java/com/redhat/labs/lodestar/service/ConfigService.java, src/main/java/com/redhat/labs/lodestar/service/EngagementService.java, src/main/java/com/redhat/labs/lodestar/service/ParticipantService.java, src/test/java/com/redhat/labs/lodestar/resource/EngagementResourceGetTest.java, src/test/java/com/redhat/labs/lodestar/resource/EngagementResourceUpdateTest.java, src/test/java/com/redhat/labs/lodestar/resource/HostingEnvironmentResourceTest.java, src/test/java/com/redhat/labs/lodestar/resource/StatusResourceTest.java, src/test/java/com/redhat/labs/lodestar/service/EngagementServiceTest.java, src/test/java/com/redhat/labs/lodestar/service/ParticipantServiceTest.java
- An API that gets engagements that are in the db but not in gitlab
- An API that tries to repost engagement data into gitlab (summary data only)
=> Add apis for gitlab retry
