rht-labs/lodestar-backend

src/main/resources/application.properties

Add the appropriate Quarkus config params for the native-image build to include the libraries required for the app to make calls to HTTPS endpoints.

Fix quarkus native ssl

---

src/main/resources/META-INF/resources/fake-config.json
src/main/resources/application.properties

run a little bit differently in dev mode. Allows developer to go around security restrictions. There is also a json file example of config data.

auto-disable security  sso in dev mode. Add a fake config file for FE

---

Jenkinsfile

This is a simple change to fix the build error `Exception in thread "main" java.lang.NoSuchMethodError: org.eclipse.aether.transfer.TransferResource.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/io/File;Lorg/eclipse/aether/RequestTrace;)V` using the latest `jenkins-slave-mvn`.

Switch mvn out for mvnw

---

src/main/java/com/redhat/labs/omp/rest/client/OMPGitLabAPIService.java

The git api was changed in the following PR:
https://github.com/rht-labs/open-management-portal-git-api/pull/34
Changing the backend to call:
/api/v1/engagements
instead of:
/api/residencies
Should be able to close https://gitlab.consulting.redhat.com/rht-labs/labs-sre/documentation/issues/98 afterwards.

Updated GIT API Path to used Engagements instead of Residencies

---

deployment/templates/mongodb-deploymentconfig.yaml
deployment/templates/mongodb-pvc.yaml
deployment/templates/mongodb-service.yaml
deployment/values.yaml

This will complete [#185](https://gitlab.consulting.redhat.com/rht-labs/labs-sre/documentation/-/issues/185).
The `omp-backend-configuration` secret will come from the runtime-config

Make MongoDB part of deployment

---

README.md
src/main/java/com/redhat/labs/omp/service/GitSyncService.java
src/main/resources/application.properties
src/test/java/com/redhat/labs/omp/resources/GitSyncResourceTest.java
src/test/java/com/redhat/labs/omp/rest/client/MockOMPGitLabAPIService.java

Issue:
When the process method is called from either the endpoint or the auto sync feature, if a REST call to the `/engagements` endpoint  returns a 400 or greater response code, a WebApplicationException is thrown.  This results in the method returning without processing any other modified engagements.
Fix:
Now catching the WebApplicationException and logging the error, the engagement, and a note saying that a refresh of data may be necessary from Git.  After logging, any other modified engagements will be processed.  Any engagements that failed to be pushed to Git API and GitLab will be tried again on the next invocation of the process method.  
Monitoring of the logged exceptions should be conducted so that we can determine if a refresh is required.
Also, incorporated and closed #52 …

Sync to Git API Error Handling

---

src/main/resources/application.properties
src/test/java/com/redhat/labs/omp/resources/ConfigResourceTest.java
src/test/resources/JwtClaimsUnknown.json
src/test/resources/application.properties

- use reader and writer roles to secure endpoints for backend
- reader and writer can access the GET methods for `/config` and `/engagements/*`
- writer can access POST and PUT methods for `/engagements/*`

Use New Roles to Secure Endpoints

---

src/test/java/com/redhat/labs/omp/config/VersionManifestConfigTest.java
src/test/java/com/redhat/labs/omp/resources/ConfigResourceTest.java
src/test/java/com/redhat/labs/omp/resources/EngagementResourceTest.java
src/test/java/com/redhat/labs/omp/resources/GitSyncResourceTest.java
src/test/java/com/redhat/labs/omp/resources/VersionResourceTest.java
src/test/java/com/redhat/labs/utils/EmbeddedMongoTest.java
src/test/java/com/redhat/labs/utils/EmbeddedMongoTestExtension.java

The tests that require a running Mongo need to make sure the instance is running before the Quarkus app is started. 
- Existing Tests now use the @EmbeddedMongoTest annotation
- The EmbeddedTestExtension is a Junit 5 Test extension that will manage the embedded Mongo instance.  It will start Mongo before running the tests, clear any data in databases (except for admin, local, and config) before each test, and then stop Mongo after the tests
- @EmbeddedMongoTest is used before the @QuarkusTest extension to insure the correct startup order
- Tests run faster because Mongo is only started and stopped once per test class using the extension
This change is required to make the update to the Backend API where it will load the Mongo DB on startup if it doesn't already have data.  Without it, the …

Embedded Mongo Test Extension

---

src/main/java/com/redhat/labs/omp/resource/GitSyncResource.java
src/main/java/com/redhat/labs/omp/service/ActiveGitSyncService.java
src/main/java/com/redhat/labs/omp/service/GitSyncService.java

- fix for checkIfActive not setting timestamp when new instance becoming active
- separated active sync logic and sync logic
- ActiveGitSyncService responsible for managing active state and triggering scheduled pushes to git
- GitSyncService responsible for interactions between EngagementService and Git API
- removed auto save toggle (did not work for multiple instances)

Bug Fix for Becoming Active as Result of Prior Active Stale/Missing

---

src/main/java/com/redhat/labs/omp/model/event/BackendEvent.java
src/main/java/com/redhat/labs/omp/model/event/EventType.java
src/main/java/com/redhat/labs/omp/resource/GitSyncResource.java
src/main/java/com/redhat/labs/omp/service/ActiveGitSyncService.java
src/main/java/com/redhat/labs/omp/service/EngagementService.java
src/main/java/com/redhat/labs/omp/service/GitSyncService.java

- added refresh mongo database to app start up if instance is active and no engagements exist in the db
- simplified communication using events and event bus
- ActiveGitSyncService, GitSyncService, and EngagementService only communicate through the Event Bus using Events
- method visibility and general cleanup

Database Population on Application Startup

---

src/main/java/com/redhat/labs/omp/model/Engagement.java
src/main/java/com/redhat/labs/omp/validation/NameValidator.java
src/main/java/com/redhat/labs/omp/validation/ValidName.java
src/test/java/com/redhat/labs/omp/validation/NameValidatorTest.java

- conforming to the current GitLab requirements for group names
- Name can contain only letters, digits, emojis, '_', '.', dash, space, parenthesis. It must start with letter, digit, emoji or '_'.
- did not implement the emojis
- regex is configurable using property `valid.name.regex` or environment variable `VALID_NAME_REGEX`

Validate Customer and Project Name

---

src/main/java/com/redhat/labs/omp/service/GitSyncService.java
src/test/java/com/redhat/labs/omp/resources/GitSyncResourceTest.java

When events are being processed from the EventBus, warnings will be logged if the execution of the consumer takes longer than 2 seconds.  This is because the event loop is being blocked.  This fix moved the main 2 offenders into a separate execution thread by using Vertx.executeBlocking clauses.
- Processing a DbRefreshRequestedEvent
- Processing a UpdateEngagementsInGitRequestedEvent
Both of these are using the REST Git API which can cause a delayed response.

Event Loop Should not be Blocked By Longer Running Processes

---

src/main/java/com/redhat/labs/omp/model/CreationDetails.java
src/main/java/com/redhat/labs/omp/model/Launch.java
src/main/java/com/redhat/labs/omp/service/EngagementService.java
src/main/java/com/redhat/labs/omp/service/GitSyncService.java

- store dates as ISO strings
- initial creation and launch dates will have date, time, and UTC/Z timezone

Change Dates to ISO Strings

---

src/main/java/com/redhat/labs/omp/model/Launch.java
src/main/java/com/redhat/labs/omp/resource/EngagementResource.java
src/main/java/com/redhat/labs/omp/service/EngagementService.java
src/test/java/com/redhat/labs/omp/resources/EngagementResourceTest.java
src/test/resources/JwtClaimsWriter.json

- launch, creation, commits, and status will not be editable from an update
- incoming data will be replaced with the data from the data store
- added launch by email
- using `user` claim for user name instead of `perferred_username` claim

Restore Immutable Engagment Fields and Minor Updates

---

src/main/java/com/redhat/labs/omp/model/GitlabProject.java
src/main/java/com/redhat/labs/omp/model/Hook.java
src/main/java/com/redhat/labs/omp/resource/StatusResource.java
src/main/java/com/redhat/labs/omp/service/EngagementService.java
src/main/resources/application.properties
src/test/java/com/redhat/labs/omp/resources/StatusResourceTest.java
src/test/java/com/redhat/labs/omp/service/EngagementServiceTest.java
src/test/resources/StatusDeleted.json
src/test/resources/StatusDeletedNoEngagement.json
src/test/resources/StatusReqValid.json
src/test/resources/application.properties

When engagements are deleted (via cronjob) they can notify the backend to remove that engagement from mongo after sharing a token.
The application can use configuration to set the token and if the token is set to the magical value of `OFF` (case sensitive) then this endpoint will be rendered useless. This will help prevent deletions in envs where they should not occur.
This also address is previous known issue where status updates could not be done for engagements with special characters. This now supports all characters by using the namespace instead of path with namespace. The namespace gives us the true customer name and engagement name.
🧀  🥂

🧀  Adds ability to delete engagements via Hook  🥂 

---

src/main/java/com/redhat/labs/omp/model/Engagement.java
src/main/java/com/redhat/labs/omp/repository/EngagementRepository.java
src/main/java/com/redhat/labs/omp/resource/EngagementResource.java
src/main/java/com/redhat/labs/omp/service/EngagementService.java
src/main/java/com/redhat/labs/omp/service/GitSyncService.java
src/test/java/com/redhat/labs/omp/resources/EngagementResourceTest.java
src/test/java/com/redhat/labs/omp/resources/GitSyncResourceTest.java

- added `lastUpdate` to engagement
- changed update to use `findOneAndUpdate` to prevent concurrent updates from overwriting data
- each create/update will set the `lastUpdate` on the engagement 
- update throws 409 status if the `engagement` has been modified by another call
- added HEAD api for an engagement - returns `last-update` attribute in headers if engagement exists

Concurrency Fixes for Engagement Updates

---

src/main/java/com/redhat/labs/omp/resource/EngagementResource.java
src/test/java/com/redhat/labs/omp/resources/EngagementResourceTest.java

- added `Access-Control-Expose-Headers` to `GET` and `HEAD` methods for `engagement`

Access-Control-Expose-Headers Header

---

src/main/java/com/redhat/labs/omp/model/GitlabProject.java

Fixes issue where status hook errors with null pointer. Apparently, the name with namespace does not get sent with the webhook event payload. This uses the path instead as it did before. Because the path may not always be correct (special characters can be removed from the path but not the name) a fallback needs to be in place which there is. The fallback sends the path to the git-api to get the engagement by path.

fix hook get by path

---

src/main/java/com/redhat/labs/omp/service/EngagementService.java

Since the status and commit history are coming from gitlab and are not editable from the front end, the `last_update` attribute should not be modified when the status/commit data is updated in the database.
The FE user will get that status when the `engagement` is refreshed.

last update should not be updated on status update

---

deployment/templates/deploymentconfig.yaml
pom.xml
src/main/java/com/redhat/labs/omp/health/BackendLivenessCheck.java
src/main/java/com/redhat/labs/omp/health/GitApiHealthCheck.java
src/main/java/com/redhat/labs/omp/resource/StatusResource.java
src/main/java/com/redhat/labs/omp/rest/client/LodeStarStatusApiClient.java
src/test/java/com/redhat/labs/omp/resources/StatusResourceTest.java
src/test/java/com/redhat/labs/omp/rest/client/MockLodeStarStatusApiClient.java

- added `GET /status`
- calls the status service `GET /api/v1/status` and returns the response.
- added liveness and readiness checks to `deploymentconfig`
- added readiness check for `git-api`

Component Status API

---

src/main/java/com/redhat/labs/omp/model/Artifact.java
src/main/java/com/redhat/labs/omp/model/Engagement.java
src/main/java/com/redhat/labs/omp/repository/EngagementRepository.java
src/main/java/com/redhat/labs/omp/resource/EngagementResource.java
src/main/java/com/redhat/labs/omp/service/EngagementService.java
src/test/java/com/redhat/labs/omp/resources/EngagementResourceTest.java

- added artifacts to the engagement model
- added `GET` API for retrieving artifact types
- `/engagements/artifact/types` - returns all unique artifact types
- `/engagements/artifact/types?suggest=<input>` - returns artifact types matching input string
- artifact type tests

Engagement Artifacts and Artifact Type APIs

---

src/main/java/com/redhat/labs/lodestar/model/Engagement.java
src/main/java/com/redhat/labs/lodestar/service/EngagementService.java
src/main/java/com/redhat/labs/lodestar/service/GitSyncService.java

- `commit_message` attribute added to engagement model
- if specified, it will be used in the git-api to set the commit message when an engagement is created/updated.

Add Commit Message to Engagement

---

src/main/java/com/redhat/labs/lodestar/exception/mapper/LodeStarGitLabAPIServiceResponseMapper.java
src/main/java/com/redhat/labs/lodestar/repository/EngagementRepository.java
src/main/java/com/redhat/labs/lodestar/rest/client/LodeStarGitLabAPIService.java
src/main/java/com/redhat/labs/lodestar/service/EngagementService.java
src/main/java/com/redhat/labs/lodestar/service/GitSyncService.java

Error Flow:
Engagement updated --> Git Sends modified Engagement to Git API --> Engagement Updated Again before Git API response processed --> Git Sync updates the Engagement in the Database with the prior (now stale) data 
The issue is that when the response from the Git API is returned, the sync sends a request to update the engagement so that the modified flags are cleared.  This works fine if the engagement has not be modified during the sync processing.  If it has been modified there is the potential of replacing the current engagement with what is now in Git.  This then will lose any changes that were waiting to be pushed to Git.

Bugfix: Git Sync Can Cause Subsequent Modifications to be Reverted

---

src/main/java/com/redhat/labs/lodestar/service/EngagementService.java

- launch was being removed because the skip check used the requested engagement rather than the currently persisted one
- commit message aggregation was also not checking against the persisted engagement causing multiple commit messages to be lost if changed within the sync interval

Bug Fixes:  Commit Message Aggregation and Launch Failure

---

src/main/java/com/redhat/labs/lodestar/service/EngagementService.java

I believe the issue we were facing was that the stream was not invoked because the map was not being used. Switch to a forEach.
Check this sonar feedback
https://sonarcloud.io/project/issues?id=rht-labs_open-management-portal-backend&open=AXV2Qh7x3fco6dPPkApW&resolved=false&sinceLeakPeriod=true&types=BUG

fix for uuid for existing projects

---

src/main/java/com/redhat/labs/lodestar/model/EngagementUser.java
src/main/java/com/redhat/labs/lodestar/repository/EngagementRepository.java
src/test/java/com/redhat/labs/lodestar/resources/EngagementResourceTest.java

- Equals method could throw null pointer if called from the API level.  Shouldn't be possible through the UI
- Repository Field should not be public
- Removed unused import from test

Sonar - Reliability and Security Fixes

---

src/main/java/com/redhat/labs/lodestar/model/EngagementUser.java
src/main/java/com/redhat/labs/lodestar/repository/EngagementRepository.java
src/main/java/com/redhat/labs/lodestar/service/EngagementService.java
src/test/java/com/redhat/labs/lodestar/resources/EngagementResourceTest.java
src/test/java/com/redhat/labs/lodestar/service/EngagementServiceTest.java

- `EngagementUser` now exposes a `reset` attribute that will trigger a user reset on the orchestration side
- `EngagementUser` now exposes a `uuid` attribute to uniquely identifier a user
- automatically sets UUIDs for `EngagementUsers` if null in mongo or on creation of new user

User Reset Implementation

---

src/main/java/com/redhat/labs/lodestar/model/Engagement.java
src/main/java/com/redhat/labs/lodestar/repository/EngagementRepository.java
src/main/java/com/redhat/labs/lodestar/resource/EngagementResource.java
src/main/java/com/redhat/labs/lodestar/service/EngagementService.java
src/test/java/com/redhat/labs/lodestar/resources/EngagementResourceTest.java
src/test/java/com/redhat/labs/lodestar/resources/GitSyncResourceTest.java
src/test/java/com/redhat/labs/lodestar/resources/StatusResourceTest.java

- on create, validates no other engagement exists with any hosting environment subdomain, if provided on `POST /engagements`
- on update, validates no other engagement exists with any hosting environment subdomain, if provided on `PUT /engagements/{uuid}`
- skips check if engagement uuid matches (i.e. skip subdomain check if the subdomain found is on the engagement being updated.

Unique Subdomain

---

.gitignore
src/main/java/com/redhat/labs/lodestar/model/Engagement.java
src/main/java/com/redhat/labs/lodestar/model/EngagementUser.java
src/main/java/com/redhat/labs/lodestar/model/HostingEnvironment.java
src/main/java/com/redhat/labs/lodestar/repository/EngagementRepository.java
src/main/java/com/redhat/labs/lodestar/resource/EngagementResource.java
src/test/java/com/redhat/labs/lodestar/resources/EngagementResourceTest.java
src/test/resources/application.properties

- added filtering options `include` and `exclude` to the following:
- `GET` `/engagements`
- `GET` `/engagements/customers/{customerName}/projects/{projectName}`
- `GET` `/engagements/{uuid}`
- Returns 400 if both `include` and `exclude` specified
- Clients can build the response they want by supplying a comma separated list of fields using the `include` 
- Clients can remove fields from the response they want by supplying a comma separated list of fields using the `exclude`
- If no lists supplied for `include` or `exclude` all fields will be returned

Add Filtering to GET APIs

---

src/main/java/com/redhat/labs/lodestar/service/EngagementService.java

removing this check because the `git-api` will look up the project based on customer/engagement names if the project id is not supplied by the `backend`.

Remove Project ID Check on Update

---

src/main/java/com/redhat/labs/lodestar/service/EngagementService.java
src/main/java/com/redhat/labs/lodestar/service/EventService.java
src/test/java/com/redhat/labs/lodestar/service/EngagementServiceTest.java
src/test/java/com/redhat/labs/lodestar/service/EventServiceTest.java

- throws bad request if customer or project name greater than 255 on create or update
- exits retry if engagement has been deleted before the next retry

BugFixes - Name Length and Retry

---

README.md
src/main/java/com/redhat/labs/lodestar/exception/mapper/LodeStarGitLabAPIServiceResponseMapper.java
src/main/java/com/redhat/labs/lodestar/model/event/EventType.java
src/main/java/com/redhat/labs/lodestar/repository/EngagementRepository.java
src/main/java/com/redhat/labs/lodestar/resource/EngagementResource.java
src/main/java/com/redhat/labs/lodestar/rest/client/LodeStarGitLabAPIService.java
src/main/java/com/redhat/labs/lodestar/service/ActiveGitSyncService.java
src/main/java/com/redhat/labs/lodestar/service/EngagementService.java
src/main/java/com/redhat/labs/lodestar/service/EventService.java
src/main/resources/application.properties
src/test/java/com/redhat/labs/lodestar/resource/EngagementResourceUpdateTest.java
src/test/java/com/redhat/labs/lodestar/resource/StatusResourceTest.java
src/test/java/com/redhat/labs/lodestar/service/ActiveGitSyncServiceTest.java
src/test/java/com/redhat/labs/lodestar/service/EngagementServiceTest.java
src/test/java/com/redhat/labs/lodestar/service/EventServiceTest.java

- Added Events to help facilitate populating/repopulating mongo with engagements from GitLab
- The get all engagements is now broken down into pages and without status and commit information so smaller amounts are retrieved from git-api
- Each returned engagement is inserted into mongo if it does not already exist
- Status and Commit information are only retrieved if inserting into mongo.  This is done asynchronously.
- Update Status and Commit Webhook now uses the same async functionality
- Refresh Database API also uses the same mechanism to populate the data
- `purgeFirst` is still available on this api
- BugFix
- allow no body in Git API REST error response

Database Population Performance Improvements Using Paging

---

README.md
src/main/java/com/redhat/labs/lodestar/model/Hook.java
src/main/java/com/redhat/labs/lodestar/service/EngagementService.java
src/main/java/com/redhat/labs/lodestar/service/EventService.java
src/main/resources/application.properties
src/test/java/com/redhat/labs/lodestar/model/HookTest.java
src/test/java/com/redhat/labs/lodestar/service/EngagementServiceTest.java
src/test/java/com/redhat/labs/lodestar/service/EventServiceTest.java
src/test/java/com/redhat/labs/lodestar/utils/MockUtils.java

- Allows the refresh of an engagement by using a GitLab push event to trigger the `backend` status hook endpoint.
- If the list of commits sent in the body of the webhook call contains a configured message, the engagement will be reloaded into the database. 
- default configured message is `manual_refresh`
- can be configured by environment variable `COMMIT_FILTERED_MESSAGE_LIST`
- If the commit list does not contain the message, it behaves the same way it always has.   If status.json was changed, the status will be updated in the database and the commits will be updated.  no other fields will be updated.

Allow engagement refresh from webhook

---

src/main/java/com/redhat/labs/lodestar/model/Hook.java
src/test/java/com/redhat/labs/lodestar/model/HookTest.java

The webhook method checks to see if the commit messages supplied have the configured messages within them. 
This fix make sure it checks that the commit message starts with the configured filtered message(s).  If it starts with the filtered message, the entire engagement will be refreshed in the database.

Refresh from Hook Should not use Equals

---

src/main/java/com/redhat/labs/lodestar/exception/mapper/BackendExceptionHandler.java

Created Exception Handler to map WebApplicationExceptions to Responses so that the stack traces are not printed in the logs for expected thrown exceptions.

Response Mapper for WebApplicationExceptions

---

.github/workflows/ci-cd.yml

Quarkus requires user roles to be set at runtime. This challenge will allow us to configure those roles at build time while also allowing default roles to be use locally. Essentially, this appends roles to the roles predefined in the code.
application.properties
```
quarkus.http.auth.policy.role-reader.roles-allowed=reader
```
in a gh secret 
```
READERS=some-other-role,avid-reader
```
after build time
```
quarkus.http.auth.policy.role-reader.roles-allowed=reader,some-other-role,avid-reader
```

Allow for application roles to be defined at build time

---

README.md
src/main/java/com/redhat/labs/lodestar/model/Artifact.java
src/main/java/com/redhat/labs/lodestar/model/Engagement.java
src/main/java/com/redhat/labs/lodestar/model/EngagementAttribute.java
src/main/java/com/redhat/labs/lodestar/model/HostingEnvironment.java
src/main/java/com/redhat/labs/lodestar/model/Score.java
src/main/java/com/redhat/labs/lodestar/model/pagination/PagedArtifactResults.java
src/main/java/com/redhat/labs/lodestar/model/pagination/PagedCategoryResults.java
src/main/java/com/redhat/labs/lodestar/model/pagination/PagedEngagementResults.java
src/main/java/com/redhat/labs/lodestar/model/pagination/PagedHostingEnvironmentResults.java
src/main/java/com/redhat/labs/lodestar/model/pagination/PagedResults.java
src/main/java/com/redhat/labs/lodestar/model/pagination/PagedScoreResults.java
src/main/java/com/redhat/labs/lodestar/model/pagination/PagedStringResults.java
src/main/java/com/redhat/labs/lodestar/model/pagination/PagedUseCaseResults.java
src/main/java/com/redhat/labs/lodestar/repository/EngagementRepository.java
src/main/java/com/redhat/labs/lodestar/repository/MongoAggregationHelper.java
src/main/java/com/redhat/labs/lodestar/resource/EngagementArtifactResource.java
src/main/java/com/redhat/labs/lodestar/resource/EngagementCategoryResource.java
src/main/java/com/redhat/labs/lodestar/resource/EngagementHostingEnvironmentResource.java
src/main/java/com/redhat/labs/lodestar/resource/EngagementResource.java
src/main/java/com/redhat/labs/lodestar/resource/EngagementScoreResource.java
src/main/java/com/redhat/labs/lodestar/resource/EngagementUseCaseResource.java
src/main/java/com/redhat/labs/lodestar/service/EngagementService.java
src/main/java/com/redhat/labs/lodestar/util/ClassFieldUtils.java
src/test/java/com/redhat/labs/lodestar/resource/EngagementResourceGetTest.java
src/test/java/com/redhat/labs/lodestar/service/EngagementServiceTest.java
src/test/java/com/redhat/labs/lodestar/utils/MockUtils.java
src/test/java/com/redhat/labs/lodestar/zrepository/EngagementRepositoryTest.java

- Created EngagementAttribute Parent class to define the following attributes:
- uuid - unique id for an attribute
- created - timestamp for the creation of the attribute
- updated - timestamp for the last update of the attribute
- engagementUuid - unique id for the attributes parent engagement
- Artifact, UseCase, Category, HostingEnvironment, and Score extend EngagementAttribute
- Created new or separated nested object resources from EngagementResource
- EngagementArtifactResource - query artifacts across engagements
- EngagementUseCaseResource - query use cases across engagements
- EngagementCategoryResource - query for category name/count
- EngagementHostingEnvironmentResource - query for hosting environments across engagements
- EngagementScoreEnvironmentResource - query for scores …

APIs for Artifacts, Use Cases, Scores, Hosting Environments

---

src/main/java/com/redhat/labs/lodestar/repository/EngagementRepository.java
src/main/java/com/redhat/labs/lodestar/service/EngagementService.java
src/test/java/com/redhat/labs/lodestar/resource/EngagementResourceUpdateTest.java
src/test/java/com/redhat/labs/lodestar/service/EngagementServiceTest.java
src/test/java/com/redhat/labs/lodestar/zrepository/EngagementRepositoryTest.java

- Launch object of Engagement is now editable after a launch to allow for a manual unlaunch
- Immutable fields moved to EngagementService so that the Engagement updated send to Mongo and GitLab will be in sync.

Allow unlaunch and Fix Potential Data Issue
